# -*- coding: utf-8 -*-
"""Exercício Text Mining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSryvh3kHeyBHeZp5MscLd8dK0Bjw2RU

# Troquei para inglês
"""

!pip install nltk
!pip install wordcloud
!pip install spacy
!python -m spacy download en_core_web_sm

import nltk
nltk.download('stopwords')
nltk.download('rslp')
from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import ToktokTokenizer
from collections import Counter
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from nltk.stem import RSLPStemmer
import spacy
nlp = spacy.load("en_core_web_sm")  # English language

"""# Os dados são de : Water bottle review dataset (FLIPKART)
https://www.kaggle.com/datasets/tharunmss/water-bottle-dataset-flipkart
"""

# Chamando o arquivo
df = pd.read_csv('cleaned_reviews.csv')
df.info()
df.sample(3)

"""# Nova seção"""

tokenizer = ToktokTokenizer()
stopwords_eng = set(stopwords.words('english'))
stopwords_eng.add('flipkart')

# Lista para armazenar os tokens de todos os depoimentos
tokens_totais = []

# Iterar sobre cada depoimento
for cleaned_review in df['cleaned_review']:
    # Tokenização do depoimento
    tokens = tokenizer.tokenize(cleaned_review)
    # Converter para minúsculas e filtrar tokens:
    #  - Remover stopwords
    #  - Manter apenas tokens que contenham apenas letras (alfanumérico) (ignora números e pontuações)
    tokens_filtrados = [token.lower() for token in tokens
                         if token.lower() not in stopwords_eng and token.isalpha()]
    tokens_totais.extend(tokens_filtrados)

# Contar a frequência dos tokens
frequencia = Counter(tokens_totais)

# Exibir as 20 palavras mais comuns
top_10 = frequencia.most_common(20)
print(top_10)

# Considerando que a variável 'frequencia' é um objeto Counter
# com os tokens e suas respectivas frequências. Se desejar usar apenas os top 10:
top_20 = dict(frequencia.most_common(20))

# Gerar a nuvem de palavras com os top 20
wordcloud = WordCloud(width=800, height=400, background_color='black', random_state=100).generate_from_frequencies(top_20)

# Exibir a nuvem de palavras
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

from nltk.stem import PorterStemmer

# Inicializa o stemmer para inglês
stemmer = PorterStemmer()

# Dicionário para armazenar o stem e a contagem agregada
stemmed_counts = {}

for word, count in top_20.items():
    # Aplica o stemming na palavra
    stem = stemmer.stem(word)
    # Agrega a contagem para o stem correspondente
    stemmed_counts[stem] = stemmed_counts.get(stem, 0) + count

print(stemmed_counts)

# Dicionário para armazenar os lemas e a contagem agregada
lemmatized_counts = {}

# Itera sobre as palavras do dicionário
for word, count in top_20.items():
    # Processa a palavra com o spaCy
    doc = nlp(word)
    # Como estamos processando uma única palavra, pegamos o lema do primeiro token
    lemma = doc[0].lemma_
    # Agrega a contagem para o lema correspondente
    lemmatized_counts[lemma] = lemmatized_counts.get(lemma, 0) + count

print(lemmatized_counts)

wordcloud = WordCloud(width=800, height=400, background_color='black', random_state=100).generate_from_frequencies(lemmatized_counts)

# Exibir a nuvem de palavras
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""# Para fazer com os títulos das reviews"""

tokenizer = ToktokTokenizer()
stopwords_eng = set(stopwords.words('english'))

# Lista para armazenar os tokens de todos os depoimentos
tokens_tot = []

# Iterar sobre cada depoimento
for title in df['title']:
    # Tokenização do depoimento
    tokens_2 = tokenizer.tokenize(title)
    # Converter para minúsculas e filtrar tokens:
    #  - Remover stopwords
    #  - Manter apenas tokens que contenham apenas letras (alfanumérico) (ignora números e pontuações)
    tokens_filt = [token.lower() for token in tokens_2
                         if token.lower() not in stopwords_eng and token.isalpha()]
    tokens_tot.extend(tokens_filt)

# Contar a frequência dos tokens
freq = Counter(tokens_tot)

# Exibir as 20 palavras mais comuns
top_20_2 = freq.most_common(20)
print(top_20_2)

# Considerando que a variável 'frequencia' é um objeto Counter
# com os tokens e suas respectivas frequências. Se desejar usar apenas os top 10:
top_20_2 = dict(freq.most_common(20))

# Gerar a nuvem de palavras com os top 10
wordcloud2 = WordCloud(width=800, height=400, background_color='black', random_state=100).generate_from_frequencies(top_20_2)

# Exibir a nuvem de palavras
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud2, interpolation='bilinear')
plt.axis('off')
plt.show()

from nltk.stem import PorterStemmer
stemmer2 = PorterStemmer()

# Dicionário para armazenar o stem e a contagem agregada
stemmed_counts2 = {}

for word, count in top_20_2.items():
    # Aplica o stemming na palavra
    stem2 = stemmer2.stem(word)
    # Agrega a contagem para o stem correspondente
    stemmed_counts2[stem2] = stemmed_counts2.get(stem2, 0) + count

print(stemmed_counts2)

# Dicionário para armazenar os lemas e a contagem agregada
lemmatized_counts2 = {}

# Itera sobre as palavras do dicionário
for word, count in top_20_2.items():
    # Processa a palavra com o spaCy
    doc = nlp(word)
    # Como estamos processando uma única palavra, pegamos o lema do primeiro token
    lemma2 = doc[0].lemma_
    # Agrega a contagem para o lema correspondente
    lemmatized_counts2[lemma2] = lemmatized_counts2.get(lemma2, 0) + count

print(lemmatized_counts2)

wordcloud = WordCloud(width=800, height=400, background_color='black', random_state=100).generate_from_frequencies(lemmatized_counts2)

# Exibir a nuvem de palavras
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()